### ISSUE TITLE
Thank you for your cppinclude project

### ISSUE THREAD

**Issue by tudou614** [cppinclude/cppinclude#1]
Hi, I checked the newest lua source code with your cppinclude,  here is the result:

Start initialization project ...
Start analyze sources ...
Start report results ...
Unresolved files:
1. "unistd.h" isn't resolved in:
        1. "loslib.c" line: 115
        2. "lua.c" line: 367
2. "windows.h" isn't resolved in:
        1. "loadlib.c" line: 157
        2. "lua.c" line: 373
3. "dlfcn.h" isn't resolved in:
        1. "loadlib.c" line: 114
4. "io.h" isn't resolved in:
        1. "lua.c" line: 372
5. "readline\history.h" isn't resolved in:
        1. "lua.c" line: 398
6. "readline\readline.h" isn't resolved in:
        1. "lua.c" line: 397
7. "sys\types.h" isn't resolved in:
        1. "liolib.c" line: 108
8. "sys\wait.h" isn't resolved in:
        1. "lauxlib.c" line: 267
Most impact files:
1 : "luaconf.h" impact to 58 file(s)
Included by:
        1 : "lua.h" line 16, impact to 57 file(s)
2 : "lua.h" impact to 57 file(s)
Included by:
        1 : "llimits.h" line 15, impact to 40 file(s)
        2 : "lobject.h" line 16, impact to 33 file(s)
        3 : "lmem.h" line 14, impact to 31 file(s)
        4 : "lzio.h" line 11, impact to 30 file(s)
        5 : "lstate.h" line 10, impact to 25 file(s)
        6 : "lauxlib.h" line 15, impact to 15 file(s)
        7 : "lualib.h" line 11, impact to 13 file(s)
        8 : "lctype.h" line 10, impact to 3 file(s)
        9 : "lapi.c" line 17
        10 : "lauxlib.c" line 25
        ... 10 of 41 details
3 : "llimits.h" impact to 40 file(s)
Included by:
        1 : "lobject.h" line 15, impact to 33 file(s)
        2 : "lmem.h" line 13, impact to 31 file(s)
        3 : "lopcodes.h" line 10, impact to 8 file(s)
        4 : "lparser.h" line 10, impact to 6 file(s)
        5 : "lundump.h" line 10, impact to 5 file(s)
        6 : "lapi.h" line 11, impact to 4 file(s)
        7 : "lctype.h" line 36, impact to 3 file(s)
        8 : "lzio.c" line 17
4 : "lprefix.h" impact to 34 file(s)
Included by:
        1 : "lapi.c" line 10
        2 : "lauxlib.c" line 10
        3 : "lbaselib.c" line 10
        4 : "lcode.c" line 10
        5 : "lcorolib.c" line 10
        6 : "lctype.c" line 10
        7 : "ldblib.c" line 10
        8 : "ldebug.c" line 10
        9 : "ldo.c" line 10
        10 : "ldump.c" line 10
        ... 10 of 34 details
5 : "lobject.h" impact to 33 file(s)
Included by:
        1 : "ltm.h" line 11, impact to 26 file(s)
        2 : "lstate.h" line 12, impact to 25 file(s)
        3 : "ldo.h" line 11, impact to 17 file(s)
        4 : "lgc.h" line 11, impact to 17 file(s)
        5 : "lstring.h" line 11, impact to 14 file(s)
        6 : "ltable.h" line 10, impact to 11 file(s)
        7 : "lfunc.h" line 11, impact to 9 file(s)
        8 : "lvm.h" line 12, impact to 8 file(s)
        9 : "llex.h" line 10, impact to 6 file(s)
        10 : "lparser.h" line 11, impact to 6 file(s)
        ... 10 of 29 details
6 : "lmem.h" impact to 31 file(s)
Included by:
        1 : "lzio.h" line 13, impact to 30 file(s)
        2 : "lapi.c" line 24
        3 : "lcode.c" line 24
        4 : "ldo.c" line 24
        5 : "lfunc.c" line 21
        6 : "lgc.c" line 22
        7 : "lmem.c" line 20
        8 : "lobject.c" line 25
        9 : "lparser.c" line 23
        10 : "lstate.c" line 24
        ... 10 of 14 details
7 : "lzio.h" impact to 30 file(s)
Included by:
        1 : "lstate.h" line 14, impact to 25 file(s)
        2 : "ldo.h" line 13, impact to 17 file(s)
        3 : "llex.h" line 11, impact to 6 file(s)
        4 : "lparser.h" line 12, impact to 6 file(s)
        5 : "lundump.h" line 12, impact to 5 file(s)
        6 : "ldo.c" line 34
        7 : "llex.c" line 28
        8 : "lundump.c" line 25
        9 : "lzio.c" line 20
8 : "ltm.h" impact to 26 file(s)
Included by:
        1 : "lstate.h" line 13, impact to 25 file(s)
        2 : "lvm.h" line 13, impact to 8 file(s)
        3 : "lapi.c" line 29
        4 : "ldebug.c" line 29
        5 : "ldo.c" line 31
        6 : "lgc.c" line 27
        7 : "lstate.c" line 28
        8 : "ltm.c" line 24
        9 : "lvm.c" line 30
9 : "lstate.h" impact to 25 file(s)
Included by:
        1 : "ldebug.h" line 11, impact to 17 file(s)
        2 : "ldo.h" line 12, impact to 17 file(s)
        3 : "lgc.h" line 12, impact to 17 file(s)
        4 : "lstring.h" line 12, impact to 14 file(s)
        5 : "lapi.h" line 12, impact to 4 file(s)
        6 : "lapi.c" line 26
        7 : "ldebug.c" line 26
        8 : "ldo.c" line 28
        9 : "ldump.c" line 18
        10 : "lfunc.c" line 23
        ... 10 of 22 details
10 : "ldebug.h" impact to 17 file(s)
Included by:
        1 : "lapi.c" line 20
        2 : "lcode.c" line 20
        3 : "ldebug.c" line 21
        4 : "ldo.c" line 20
        5 : "lfunc.c" line 17
        6 : "lgc.c" line 18
        7 : "llex.c" line 19
        8 : "lmem.c" line 17
        9 : "lobject.c" line 23
        10 : "lparser.c" line 19
        ... 10 of 17 details
... 10 of 35 files

---------------------------------
I have 3 issues:
(1) what does it means like this "windows.h" isn't resolved in:",""io.h" isn't resolved in:".........
(2) why only 10 files of the 28 files were detected ? But the result showed "... 10 of 35 files"
(there are only 28 header files)
(3) Other *.h files belong to windows were not detected, maybe called "External Dependencies"
(ex. in the limits.h of LUA src, there are 2 include, #include <limits.h> and #include <stddef.h>)

impact to -> maybe you want to say "impact on" ?

**Comment by cppinclude** [comment]
> (1) what does it means like this "windows.h" isn't resolved in:",""io.h" isn't resolved in:".........

it means that _cppinclude_ didn’t find _windows.h_ file in same directory where is _loadlib.c_ or in includes directories ( https://github.com/cppinclude/cppinclude#include_dirs ). It’s system file, you can add it to ignore ( https://github.com/cppinclude/cppinclude#ignore_files )

> (2) why only 10 files of the 28 files were detected ? But the result showed "... 10 of 35 files" (there are only 28 header files)

The tool analyzes all files but prints 10 items by default. You can change the limit or set unlimited: _cppinclude --report_limit=0 –report_details_limit=0_  . Output will be: [lua.txt](https://github.com/cppinclude/cppinclude/files/5152738/lua.txt)

> (3) Other *.h files belong to windows were not detected, maybe called "External Dependencies"

_cppinclude_ detects only C++ and C Standard Library headers ( https://en.cppreference.com/w/cpp/header ,  https://en.cppreference.com/w/c/header ). In current release it doesn’t detect Windows or Unix headers, you can set paths to files in _include_dirs_ or add to _ignore_files_

> (ex. in the limits.h of LUA src, there are 2 include, #include <limits.h> and #include <stddef.h>)

About _limits.h_, it’s a bug because C Standard Library has file with same name. Thanks for your comment, we will fix it in future release

>impact to -> maybe you want to say "impact on" ?

Thanks, it's a typo :) Were are not native English speakers

**Comment by cppinclude** [comment]
@tudou614 please try version 0.2.0. If everything is ok, can we close the ticket ?
