### ISSUE TITLE
Windows Security quarantined the built .exe as a trojan for 32-bit version

### ISSUE THREAD

**Issue by Thaigun** [cppinclude/cppinclude#15]
After running build.bat, Windows defender quarantined cppinclude.exe as a trojan. This is the learn more page that was linked: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aScript%2fWacatac.B!ml&threatid=2147735503

**Comment by cppinclude** [comment]
We can't reproduce the issue. Can you describe your scenario ? 

We tried to reproduce using Windows 10 with lasted updates and run build.bat via cmd and PowerShell using Visual Studio 16 2019 with and without Administrator role.

Also we checked the exe file with different antiviruses https://www.virustotal.com/gui/file/9754febe31c59fa516f25519263cdde81e7f58b3e44e827b81ee87df46e8b23f/detection

**Comment by Thaigun** [comment]
I tried to reproduce it on the same machine but it didn't happen again. Unfortunately, I don't have an access to that computer anymore. It was an up-to-date Win 10 Pro and your setup sounds similar to what I had.

**Comment by cppinclude** [comment]
We reproduced the issue. Steps for reproducing: 
1. Download zip file with 32-bit application
2. Unzip the file

Workaround:
1. Download zip file with 64-bit application
2. Unzip the file
