### ISSUE TITLE
Project licensing

### ISSUE THREAD

**Issue by ranisalt** [cppinclude/cppinclude#16]
Hello! First of all, thanks for the great project, I'm sure it has been helping a lot of people out there :clinking_glasses: 

I would like to package this program for Arch Linux, however, I have to specify the license used by the project and it currently has nothing. Therefore, I ask that you kindly add a license to the project, otherwise it gets in a gray area in regards to distribution (IIRC it is copyrighted by default and not legally redistributable).

Thanks!

**Comment by cppinclude** [comment]
Hello,

Sorry for long answer, we had long vacation. Yes you can include the tool. We decided to use MIT license

Thanks!

**Comment by ranisalt** [comment]
Neat! Arch Linux and Arch-based users can now install [cppinclude v0.5.0 from the AUR](https://aur.archlinux.org/packages/cppinclude/) :)
