### ISSUE TITLE
feature request // add ability to check project using compile_commands.json 

### ISSUE THREAD

**Issue by snikulov** [cppinclude/cppinclude#6]
Hello,

It would be great to have the ability to invoke your tool with [compile_commands.json](https://clang.llvm.org/docs/JSONCompilationDatabase.html) as a project definition.
It'll be a good feature for integrating your tool with dozens CMake-able projects.

**Comment by cppinclude** [comment]
Hello, thanks for your comment, we have this feature in backlog and we will add it in next release

**Comment by cppinclude** [comment]
Hi @snikulov , it was added in 0.3.0 release
