### ISSUE TITLE
CMake: install functionality is missing 

### ISSUE THREAD

**Issue by jenisys** [cppinclude/cppinclude#9]
CMake has a standard way to install things that were built (and to pack things which is missing, too).
By providing such a section, you could install the `cppinclude` executable via the CMake build-script instead of doing by hand in the `build.sh` shell script.

EXAMPLE:

```bash
# -- RECIPE: build.sh (with replaced last step)
$ cd build
$ cmake ../src/ -DCMAKE_BUILD_TYPE=Release
$ cmake --build . --config Release
$ cmake --build . --target install
```

OR (with a thin wrapper around cmake using [cmake-build](https://github.com/jenisys/cmake-build)):

```bash
# -- COMPLETE CYCLE: Build the CMAKE_BUILD_TYPE=Release variant and installing it.
$ cd src
$ export CMAKE_BUILD_CONFIG=release
$ cmake-build
$ cmake-build install --prefix=$PWD/.installed
...
cmake --build . --target install

# -- ALTERNATIVE: build and install in one step (last two steps executed in sequence after each other)
$ cmake-build build install --prefix=$PWD/.installed
```

**Comment by cppinclude** [comment]
Thanks, It was added in commit 7a4a7b1220324572566023f0d3ad2e3bcc2589cb
